SetOutPath $INSTDIR\lib\coq\user-contrib\ZFC
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Axioms.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Axioms.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Axioms.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Cartesian.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Cartesian.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Cartesian.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Constructive.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Constructive.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Constructive.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Hierarchy.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Hierarchy.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Hierarchy.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Omega.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Omega.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Omega.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Ordinal_theory.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Ordinal_theory.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Ordinal_theory.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Plump.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Plump.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Plump.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Replacement.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Replacement.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Replacement.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Russell.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Russell.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Russell.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Sets.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Sets.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\Sets.vo
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\zfc.glob
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\zfc.v
FILE C:\cygwin_coq_platform\home\runneradmin\.opam\_coq-platform_.2021.02.1\lib\coq\user-contrib\ZFC\zfc.vo
