name: Debug Hello World Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_hello_world_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create hello.txt
        run: echo "Hello World again" > hello.txt
      - name: Upload hello.txt as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-artifact
          path: hello.txt

  print_hello_world:
    runs-on: ubuntu-latest
    needs: create_hello_world_artifact
    steps:
      - name: Download hello-world-artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world-artifact
          path: ./artifact
      - name: Print hello.txt contents
        run: cat ./artifact/hello.txt
