# Main doc: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions
# Runners spec: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
# Glob expressions: https://github.com/actions/toolkit/tree/main/packages/glob

name: MacOS

###############################################################################
# Schedule:
# Push on main branch
###############################################################################
on:
  push:
    branches:
      - 8.18-macos
  pull_request:
  workflow_dispatch:

###############################################################################
# Platform script options shared among all jobs
###############################################################################
env:
  COQREGTESTING: y

###############################################################################
# Builds Windows installer
###############################################################################
jobs:
  MacOS_platform:
    name: MacOS
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Git checkout install scripts
        uses: actions/checkout@v3
        with:
          path: main
          ref: 8.18-macos

      - name: Git checkout Coq platform
        uses: actions/checkout@v3
        with:
          repository: coq/platform
          ref: main
          path: platform
          fetch-depth: 1

      - name: Update XCode installation
        if: always()
        shell: bash
        run: |
          sudo rm -rf /Library/Developer/CommandLineTools
          xcode-select --install

      # Another fix suggested by platform, pkg-config may not be registering new libraries
      - name: Uninstall all brew packages to fix pkg-config
        if: always()
        shell: bash
        run: brew uninstall $(brew list)

      # Updated bash is necessary for the platform create_installer script.
      - name: Install Bash 4 and GNU sed on Mac
        if: always()
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update
      
          brew install bash
          brew install gnu-sed
      
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
          echo "/usr/local/bin/bash" >> $GITHUB_PATH

      - name: fix platform version by reset to specific commit
        shell: bash
        run: |
          cd platform
          git --version
          dir
          git status
          git reset --hard 6f85b7ffb0
          cd ..

      # Add placeholder for dmg,app name as well as package pick for readme
      - name: Change switch name in installer script
        if: always()
        shell: bash
        run: |
          sed -i 's/DMG_NAME=".*/DMG_NAME="Waterproof_Background"/' platform/macos/create_installer_macos.sh
          sed -i 's/APP_NAME=".*/APP_NAME="Waterproof_Background.app"/' platform/macos/create_installer_macos.sh
          cat platform/macos/create_installer_macos.sh

      - name: Missing dependency
        if: always()
        shell: bash
        run: | 
          sed -i '/^### GTK sourceview.*/i add_folder_recursively \"/Users/runner/.opam/CP.2024.01.0~8.18~2023.11/\" \"lib/sexplib0\"' platform/macos/create_installer_macos.sh
          cat platform/macos/create_installer_macos.sh

      # - name: Missing function from platform script
      #   if: always()
      #   shell: bash
      #   run: | 
      #     sed -i '/^###################### Adding stuff.*/i function add_folder_recursively {\n  echo \"Copying files from folder \$1/\$2 ...\"\n  mkdir -p \"\${RSRC_ABSDIR}/\$2/\"\n  cp -R \"\$1/\$2/\" \"\${RSRC_ABSDIR}/\$2/\"\n}' platform/macos/create_installer_macos.sh
      #     cat platform/macos/create_installer_macos.sh
          

      - name: Run coq platform make script
        if: always()
        shell: bash
        run: |
          sh platform/coq_platform_make.sh -parallel=p -jobs=2 -compcert=n -extent=i -pick="8.18~2023.11" -set-switch=y

      - name: Activate switch
        if: always()
        shell: bash
        run: |
          opam switch CP.2024.01.0~8.18~2023.11
          eval $(opam env)
          opam switch show
      
      - name: Install packages for installer script
        if: always()
        shell: bash
        run: |
          pip3 install macpack
          brew install findutils
          brew install coreutils

      - name: Update PATH variable
        if: always()
        shell: bash
        run: |
          cd /Users/runner/.opam
          ls
          echo "/Users/runner/.opam" >> $GITHUB_PATH

      # - name: Install coq-serapi
      #   if: always()
      #   shell: bash
      #   run: opam install -y coq-serapi.8.17.0+0.17.0

      - name: Install coq-lsp
        if: always()
        shell: bash
        run: opam install -y coq-lsp.0.1.9+8.18

      - name: Install coq-waterproof
        if: always()
        shell: bash
        run: opam pin add -y https://github.com/impermeable/coq-waterproof.git#2.1.1+8.18
      
      # - name: Check coq installed
      #   if: always()
      #   shell: bash
      #   run: coqc --version
          
      # Create installer with no additional packages for now just as a test
      - name: Create installer
        if: always()
        shell: bash
        run: |
          cd platform
          bash macos/create_installer_macos.sh

      # How does signing the installer work now? -sign and -signcert are options for the create installer script

      # - name: Sign the installer
      #   run: |
      #     New-Item -ItemType directory -Path certificate
      #     Set-Content -Path certificate\certificate.txt -Value '${{ secrets.CODE_SIGNING_CERTIFICATE }}'
      #     certutil -decode certificate\certificate.txt certificate\certificate.pfx
      #     & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f certificate\certificate.pfx /p '${{ secrets.CODE_SIGNING_CERTIFICATE_PASS }}' C:\installer\*.exe
      #     Remove-Item -Path certificate\*

      - name: 'Upload Artifact'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'MacOS DMG Installer'
          path: platform/macos_installer/*.dmg
          retention-days: 5
