# This is a basic workflow to help you get started with Actions

name: MacOS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - macos
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

###############################################################################
# Platform script options shared among all jobs
###############################################################################
env:
  COQREGTESTING: y

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Ubuntu_platform:
    name: MacOS
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          
      - name: Git checkout install scripts
        uses: actions/checkout@v2
        with:
          path: main
          
      - name: Git checkout Coq platform
        uses: actions/checkout@v2
        with:
          repository: coq/platform
          path: platform

      - name: Cache opam/coq
        id: cache-opam
        uses: actions/cache@v3
        env:
          cache-name: cache-opam-modules
        with:
          path: ~/.opam
          key: ${{ runner.os }}-build-${{ env.cache-name }}-no_install

      - name: Install homebrew and make
        shell: bash
        run: |
          pwd
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update
          brew install make
          brew install gcc
          brew install unzip
          if [[ $(uname -m) == 'arm64' ]]; then
            export PATH=/opt/homebrew/bin:$PATH
          fi

      #Github actions uses bash 3 instead of bash 4 which is needed for the installer script :) 
      - name: Install Bash 4 and GNU sed on Mac
        run: |
          brew install bash
          brew install gnu-sed

          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

      - name: Install Opam
        run: |
          brew install opam

      - name: Set switch name in coq platform
        shell: bash
        run: |
          echo COQ_PLATFORM_SWITCH_NAME=coq_for_waterproof >> platform/package_picks/coq_platform_switch_name.sh
          cat platform/package_picks/coq_platform_switch_name.sh

      - if: ${{ steps.cache-opam.outputs.cache-hit != 'true' }}
        name: Run coq platform make
        shell: bash
        run: |
          pwd
          cd platform
          chmod +x coq_platform_make.sh
          ./coq_platform_make.sh -extent=b -parallel=p -jobs=2 -vst=n -compcert=n -pick="8.14~2022.01" -set-switch=y 

      - if: ${{ steps.cache-opam.outputs.cache-hit != 'true' }}
        name: Install serapi
        shell: bash
        run: |
          opam install -y coq-serapi
          opam install -y coq-coquelicot

#      - name: Install Waterproof library
#       shell: bash
#        run: |
#          git clone https://github.com/impermeable/coq-waterproof
#          cd coq-waterproof
#          make
#          make install
#          cd ..
#          rm -rf coq-waterproof

      - name: Install system utilities
        run: |
          brew install findutils
          brew install coreutils
          pip3 install macpack
#          brew install adwaita-icon-theme

      - name: Create installer
        shell: bash
        run: |
          cd platform
          opam switch coq_for_waterproof
          chmod +x macos/create_installer_macos.sh
          ./macos/create_installer_macos.sh
          cd ..


      - name: 'Upload Artifact'
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: 'MacOs installer Shell Script'
          path: platform/macos/*.dmg
          retention-days: 5
          
