
name: Print Hello World Artifact

on:
  workflow_call:
    inputs:
      run_id:
        description: 'Workflow run ID to download artifact from'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Workflow run ID to download artifact from'
        required: true
        type: string

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print run id
        run: echo "Run ID is ${{ inputs.run_id }}"
      - name: Download hello-world-artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world-artifact
          path: ./artifact
          github-token: ${{ secrets.READ_ACCESS_FOR_ARTIFACTS }}
          run-id: ${{ inputs.run_id }}
      - name: Print hello.txt contents
        run: cat ./artifact/hello.txt
