name: Print Hello World Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - test-installer

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Download hello-world-artifact
        uses: actions/download-artifact@v4
        with:
          name: hello-world-artifact
          path: ./artifact
      - name: Print hello.txt contents
        run: cat ./artifact/hello.txt
