# Main doc: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions
# Runners spec: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners
# Glob expressions: https://github.com/actions/toolkit/tree/main/packages/glob

name: Windows

###############################################################################
# Schedule:
# Workflow runs on pushes to main and to waterproof_3.0.0+9.0 branch
###############################################################################
on:
  push:
    branches:
      - waterproof_3.0.0+9.0
      - main
  pull_request:
  workflow_dispatch:

###############################################################################
# Platform script options shared among all jobs
###############################################################################
env:
  COQREGTESTING: y

###############################################################################
# Builds Windows installer
###############################################################################
jobs:
  Windows_platform:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          #- '32'
          - '64'

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Git checkout install scripts
        uses: actions/checkout@v3
        with:
          path: main
          ref: waterproof_3.0.0+9.0

      - name: Some steps for debugging
        shell: cmd
        run: |
          cd main
          dir
          cd ..

      - name: Git checkout Coq platform
        uses: actions/checkout@v3
        with:
          repository: coq/platform
          ref: main
          path: platform
          fetch-depth: 0

      # - name: fix platform version
      #   shell: cmd
      #   run: |
      #     cd platform
      #     git checkout 483a341
      #     cd ..

      - name: Set switch name in coq platform
        shell: cmd
        # We need to output without a (windows style new line here) else bash will complain AND we rely on the fact that the file has a trailing new line.
        run: |
          echo | set /p dummyName="COQ_PLATFORM_SWITCH_NAME=wp" >> platform\package_picks\coq_platform_switch_name.sh
          type platform\package_picks\coq_platform_switch_name.sh

        # sed -i 's/\s\sInstallDir\s"C:\\\${MY_PRODUCT}"/  InstallDir "C:\\\\cygwin_wp\\\\home\\\\runneradmin\\\\.opam\\\\wp"/g' platform/windows/Coq.nsi
      - name: Set default install directory
        shell: cmd
        run: |
          sed -i 's/\s\sInstallDir\s"C:\\\${MY_PRODUCT}"/  InstallDir "C:\\cygwin_wp\\home\\runneradmin\\.opam\\wp"/g' platform/windows/Coq.nsi
          cat platform/windows/Coq.nsi

      - name: Copy platform pick script and icon to right place
        shell: cmd
        run : |
          copy main\package-pick-9.0~wp.sh platform\package_picks\package-pick-9.0~wp.sh
          copy main\Waterproof.ico platform\windows_installer\Waterproof.ico

      - name: Missing dependency
        shell: cmd
        run: |
          sed -i '/^###################### Create installer.*/i add_folder_recursively \"/home/runneradmin/.opam/wp/\" \"lib/sexplib0\" \"files_coq-waterproof\"' platform/windows/create_installer_windows.sh
          cat platform/windows/create_installer_windows.sh

      - name: Fix license to rocq-core
        shell: cmd
        run: |
          sed -i 's$cp source/coq/LICENSE$echo \"---- going to source rocq-core ----\"\nopam source --dir=source/rocq-core rocq-core.9.0.0\ncp source/rocq-core/LICENSE$g' platform/windows/create_installer_windows.sh
          cat platform/windows/create_installer_windows.sh

      - name: Define product name
        shell: cmd
        run: |
          sed -i 's$define MY_PRODUCT \"Coq-Platform$define MY_PRODUCT \"Waterproof-dependencies$g' platform/windows/Coq.nsi
          sed -i 's$define OUTFILE \"Coq-Platform-release-\${RELEASE}-version\${VERSION}-Windows-\${ARCH}.exe$define OUTFILE \"Waterproof-dependencies-\${VERSION}-Windows-\${ARCH}.exe$g' platform/windows/Coq.nsi
          sed -i 's$define MUI_ICON \"coq.ico$define MUI_ICON \"Waterproof.ico$g' platform/windows/Coq.nsi
          cat Coq.nsi

      - name: Comment compcert and coqide
        shell: cmd
        run: |
          sed -i 's$cp source/coq-compcert/LICENSE coq-compcert-license.txt$#cp source/coq-compcert/LICENSE coq-compcert-license.txt$g' platform/windows/create_installer_windows.sh
          sed -i 's$cp "source/\${ide_name}/$#cp "source/\${ide_name}/$g' platform/windows/create_installer_windows.sh
          cat platform/windows/create_installer_windows.sh

      - name: Run coq platform make windows
        shell: cmd
        run: platform\coq_platform_make_windows.bat -destcyg=C:\cygwin_wp -arch=${{matrix.architecture}} -extent=i -parallel=p -jobs=2 -vst=n -compcert=n -pick="9.0~wp" -set-switch=y

      - name: Copy scripts to places that are easy to reach from within cygwin
        shell: cmd
        run: |
          dir C:\
          dir C:\cygwin_wp
          dir C:\cygwin_wp\home
          dir C:\cygwin_wp\home\runneradmin
          mkdir C:\cygwin_wp\home\runneradmin\wpdinstaller\
          mkdir C:\cygwin_wp\home\runneradmin\wpdinstaller\test_files
          copy main\* C:\cygwin_wp\home\runneradmin\wpdinstaller\
          copy main\test_files\* C:\cygwin_wp\home\runneradmin\wpdinstaller\test_files\

      - name: Create symlink
        if: always()
        shell: cmd
        run: |
          echo "Create symbolic links..."
          C:\cygwin_wp\bin\bash --login -c "ln -s /home/runneradmin/.opam /opam"
          C:\cygwin_wp\bin\bash --login -c "ls /opam"

      # - name: Install coq-lsp
      #   if: always()
      #   shell: cmd
      #   run: |
      #     C:\cygwin_wp\bin\bash --login -c "opam install -y coq-lsp.0.2.3+9.0"

      - name: Install coq-waterproof
        if: always()
        shell: cmd
        run: |
          C:\cygwin_wp\bin\bash --login -c "opam pin add -y https://github.com/impermeable/coq-waterproof.git#3.0.0+9.0"

      # - name: Create installer - comment out coqide
      #   if: always()
      #   shell: cmd
      #   run: |
      #     dir
      #     dir C:\cygwin_wp\home\runneradmin\
      #     dir C:\cygwin_wp\home\runneradmin\wpdinstaller\
      #     dir C:\cygwin_wp\platform\
      #     dir C:\cygwin_wp\home\runneradmin\platform\
      #     dir C:\cygwin_wp\wpdinstaller
      #     C:\cygwin_wp\bin\bash --login -c "cd ../../platform && sed -i 's$cp source/coqide/ide/coqide/coq.ico files/bin/$#cp source/coqide/ide/coqide/coq.ico files/bin/$g' windows/create_installer_windows.sh && sed -i 's$cp source/coqide/ide/coqide/coq.ico .$#cp source/coqide/ide/coqide/coq.ico .$g' windows/create_installer_windows.sh && cat windows/create_installer_windows.sh"
      #     C:\cygwin_wp\bin\bash --login -c "cd ../../platform && windows/create_installer_windows.sh && mkdir /cygdrive/c/installer && cp windows_installer/*exe /cygdrive/c/installer/"

      - name: Create installer
        if: always()
        shell: cmd
        run: |
          dir
          dir C:\cygwin_wp\home\runneradmin\
          dir C:\cygwin_wp\home\runneradmin\wpdinstaller\
          dir C:\cygwin_wp\platform\
          dir C:\cygwin_wp\home\runneradmin\platform\
          dir C:\cygwin_wp\wpdinstaller
          C:\cygwin_wp\bin\bash --login -c "cd ../../platform && windows/create_installer_windows.sh && mkdir /cygdrive/c/installer && cp windows_installer/*exe /cygdrive/c/installer/"

      - name: 'Upload Artifact'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 'Windows installer ${{matrix.architecture}} bits'
          path: C:\installer\*.exe
          retention-days: 5
